openapi: 3.0.0
info:
  description: |
    Applicacion REST API de Delilah Resto 
  version: 1.0.0-oas3
  title: Delilah Resto
  contact:
    name: Daniel Rodriguez
    email: darodweb@gmail.com
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
tags:
  - name: clientes
  - name: pedidos
  - name: usuarios
  - name: productos
servers:
  - url: http://delilahresto.com
paths:
  /clientes:
    get:
      description: Obtiene un listado de clientes
      responses:
        200:
          description: Resultado satisfactorio
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/clientes'
  /cliente/{id}:
    get:
      description: Obtiene un cliente por ID
      parameters:
      - in: path
        name: id
        required: true
        schema:
          type: integer
          format: int64
          minimum: 1
      responses:
        200:
          description: Respuesta satisfactoria.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/cliente'
  /cliente:              
    post:
      description: Operacion para crear un nuevo cliente.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                Nombre:
                  type: string
                Apellido:
                  type: string
                Correo Electronico:
                  type: string
                Telefono:
                  type: integer
                Direccion de Envio:
                  type: string
      responses:
        201:
          description: Cliente creado satisfactoriamente.
  /pedidos:
    get:
      description: Obtiene un listado de clientes
      responses:
        200:
          description: Resultado satisfactorio
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/pedidos'        
  /pedidos/{id}:
    get:
      description: Obtiene un pedido por ID
      parameters:
      - in: path
        name: id
        required: true
        schema:
          type: integer
          format: int64
          minimum: 1
      responses:
        200:
          description: Respuesta satisfactoria.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/pedido'         
          
components:
  schemas:
    cliente:
      type: object
      properties:
        ID:
          type: integer
          example: 123
        Nombre:
          type: string
        Apellido:
          type: string
        Correo Electronico:
          type: string
        Telefono:
          type: integer
        Direccion de Envio:
          type: string
    clientes:
      type: array
      items:
        properties:
          ID:
            type: integer
            example: 123
          Nombre:
            type: string
          Apellido:
            type: string
          Correo Electronico:
            type: string
          Telefono:
            type: integer
          Direccion de Envio:
            type: string
    pedido:
      type: object
      properties:
        ID:
          type: integer
          example: 123
        Foto:
          type: string
        Articulos:
          type: array
          items:
            type: array
            Foto: string
            Descripcion: string
            Precio: integer
        Cantidad:
          type: integer
        Total:
          type: integer
        Estado:
          type: string
          example: Nuevo
        Forma de Pago:
          type: string
        Direccion:
          type: string
        Usuario:
          type: string
        Correo Electronico:
          type: string
        Telefono:
          type: integer
    pedidos:
      type: array
      items:
        properties:
          Estado:
            type: string
          Hora:
            type: string
          Numero:
            type: integer
          Descripcion:
            type: string
          Total:
            type: integer
          Usuario:
            type: string
          Direccion:
            type: string
    producto:
      type: object
      properties:
        Foto:
          type: string
        Descripcion:
          type: string
        Precio:
          type: integer
    productos:
      type: array
      items:
        properties:
          Foto:
            type: string
          Descripcion:
            type: string
          Precio:
            type: integer

